--- 
title: 'Open Science: An Introduction for Biology'
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
description: An introductory, undergraduate text on the theory and principles of Open
  Science, produced for for the Biology Department at the University of British Columbia,
  Okanagan.
---

# Welcome {-}

This text was built to accompany the first year of the Biology undergraduate degree program at UBC Okanagan. It\'s aim is to introduce learners to core considerations in the pursuit of open scientific practices. It\'s divided into three sections, the first exploring principles and concepts associated with Open Science, the second and third looking at these principles and concepts in practice with UBC and Canadian examples.

## Copyright {-}

This work is licenced under the Creative Commons [Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)

Please use the following for citing this document:

Hanna, S., Pither, J., Vis-Dunbar, M. (2021). *Open Science. An introduction for Biology*. [https://ubco-biology.github.io/OS-Introduction/](https://ubco-biology.github.io/OS-Introduction/)

All source files are available [https://github.com/ubco-biology/OS-Introduction](https://github.com/ubco-biology/OS-Introduction).

## UBCO Biology open materials {-}

This resource is part of a larger project to host UBCO Biology lab materials in an open, accessible format.

All BIOL open materials can be found at [https://ubco-biology.github.io/](https://ubco-biology.github.io/)

## Conventions {-}

<div class = "takeAway">
Highlights and key take aways from the discussion.
</div>

<div class = "note">
Further insights or notes on the discussion.
</div>

<div class = "osexample">
Examples of Open Science in practice.
</div>

<div class = "osexercise">
Exercises to work through.
</div>

